baseURL = "https://bizspotus.site/"
languageCode = "en-us"
title = "BizSpotUs"
theme = "ananke"
author = "Manoj"

[params]
description = "Explore top insurance plans for health, life, auto, pet and home. Compare options and find affordable coverage to protect what matters most."



[[menu.main]]
  name = "About Us"
  url = "https://bizspotus.site/about/"
  weight = 10

[[menu.main]]
  name = "Contact Us"
  url = "https://bizspotus.site/contact/"
  weight = 20
  
  [[menu.main]]
  name = "Privacy Policy"
  url = "https://bizspotus.site/privacy-policy/"
  weight = 30
  



