baseURL = "https://bizspotus.site/"
languageCode = "en-us"
title = "BizSpotUs"
theme = "ananke"
author = "Manoj"
[[menu.main]]
  name = "About us"
  url = "https://bizspotus.site/about/"
  weight = 10

[[menu.main]]
  name = "Contact Us"
  url = "https://bizspotus.site/contact/"
  weight = 20
  
  [[menu.main]]
  name = "Privacy Policy"
  url = "https://bizspotus.site/privacy-policy/"
  weight = 20

